
-- +migrate Up
CREATE TABLE IF NOT EXISTS genres(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(256)
);

CREATE TABLE IF NOT EXISTS accounts(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  genre_id INT NOT NULL,
  amount INT NOT NULL,
  description TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(32) NOT NULL
);

-- +migrate Down
DROP TABLE genres, accounts, users;